name: CI

on: [push, pull_request]

jobs:
  backend:
    name: Backend (Django)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd backend
          python manage.py migrate --noinput
          python manage.py test --verbosity 2

  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install & test
        run: |
          cd frontend
          npm ci || npm i
          npm run test -- --run
      - name: Build
        run: |
          cd frontend
          npm run build
